### PR TITLE
Use IPlan interface

### PR DESCRIPTION
**Pull request by crookse**

### CODE REVIEW

**Comment by crookse** [comment]
i couldn't get the undefined stuff to shut up, so i made the signatures `Function | null`. not sure if this is the right way to go. i'll keep working on this though

**Comment by crookse** [comment]
Actually, maybe this is the right way to go. otherwise we'd have to add in a bunch of conditionals to make the "Object is possibly undefined" errors go away. Thoughts? @Guergeiro @ebebbington

**Comment by Guergeiro** [comment]
If you make sure that it's not possible for the type to be null/undefined when those errors occur, just add a exclamation mark!
```typescript
function foo(opt?: string) {
  console.log(opt.length); // errors because of object undefined
}
```
```typescript
function foo(opt?: string) {
  console.log(opt!.length); // works because there is no way that this variable will be null
}
```
This assumes that no code in our codebase would ever call that passing an undefined/null, but what if we add more features and can't guarantee that? We could go around the issue but that would change the function signature.
```typescript
someHook(cb: Function, title?: string) {
  if (title != null) {
    console.log(title);
  }
  // Do whatever with cb
}
someHook(someFunc());
someHook(someFunc(), "This is someFunc()");
```

**Comment by ebebbington** [comment]
The use of `!` might actually prove useful... i've only heard of it until now, nice shout @Guergeiro !

**Comment by ebebbington** [comment]
@crookse There's also 2 instances in `src/test_case.ts` where `plan` is using `any`, maybe we could use `plan: ITestPlan` for those now

**Comment by crookse** [comment]
> What happens if user does `someHook(someFunc(), someFunc())`?

with the following code:

```
    Rhum.testPlan("test plan", () => {
      Rhum.testSuite("test suite", () => {
        function test() {
          console.log("tesT");
        }
        Rhum.testCase(test(), test());
      });
    });
```

Screen Shot 2020-06-22 at 07 10 38

**Pull request merged**
