### PR TITLE
Issue #19 non-public functionality

### LINKED ISSUE #19: Ability to test non-public members
## Summary

What: I've found in testing that there is sometimes a need to invoke a non-public member. We should make a function that makes non-public members public.

Why: Sometimes I'll find that I need to test a non-public method or check a non-public property. Adding the ability to "rewire" a class and make its members public would be useful in testing. For example, you could test that a public method calls a protected method. The public method basically covers the protected method, but what if you want to test protected method as its own unit?

## Acceptance Criteria

- [ ] New Rhum function to make protected members public
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by crookse**
Fixes #19 

**Description**

* Adds `getNonPublicPropertyValue()`
* Adds `invokeNonPublicMethod()`
* Adds tests to test the above new methods

### CODE REVIEW

**Review by ebebbington — APPROVED** [review]
Nice one!

**Comment by Guergeiro** [comment]
I'm against this change. There's a reason why **private**/**public**/**protected** signatures exist. Making this kind of change will violate encapsulation in OOP. 
If something needs to be accessed it should be either by using Getters/Setters or making the attributes public. Using the latter is the *"lazy"* way, btw.

I would find the specific points trying to access and provide Getters for them.

**Comment by crookse** [comment]
@Guergeiro, so you don't see a use case to test non public methods?

**Comment by ebebbington** [comment]
I would have to disagree with @Guergeiro, it's not as if private/protected methods are accessible all the time - you'd have to directly explicitly use rhum to do this - plus, we can't count on **other** API's having getters and setters.

**Comment by Guergeiro** [comment]
> @Guergeiro, so you don't see a use case to test non public methods?

Testing private methods should be done with Reflection and not with a method that changes the class itself.

**Comment by crookse** [comment]
so should we mimic a reflection API?

**Comment by Guergeiro** [comment]
> I would have to disagree with @Guergeiro, it's not as if private/protected methods are accessible all the time - you'd have to directly explicitly use rhum to do this - plus, we can't count on **other** API's having getters and setters.

That method is an API for the end user... That's the issue. An API shouldn't expose everything to the user, specially something which is related to the framework internal behaviour and not useful in anyway besides framework maintainers.

**Comment by ebebbington** [comment]
Yeah i guess i see your point - i mean we take that approach with drashland modules already (or any code)

**Comment by crookse** [comment]
Breno makes a good point. we will add documentation on how to reflect classes to test non-public members, but we will not be exposing an API to do it for users.

**Pull request closed without merging**
